/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Register;

import SignIn.SignIn;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Admin
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    class ThaoTac {

        public Connection ketNoi() throws ClassNotFoundException, SQLException {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/epj2_game", "root", "");
            return con;
        }
    }

    public Register() {
        initComponents();
        this.setTitle("Register");
        setBounds(200, 200, 1125, 900);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Tên đăng nhập");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 30, 160, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("Mật khẩu");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 150, 130, 50);

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(110, 90, 310, 40);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 0));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Project\\src\\Register\\154751298_262059552045795_1344398970444976006_n.png")); // NOI18N
        jButton2.setText("Register");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(360, 780, 160, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("Ảnh đại diện");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 410, 150, 70);

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 0));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Project\\src\\Register\\login.PNG")); // NOI18N
        jButton3.setText("Login now");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(600, 780, 160, 40);

        jTextField4.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(700, 90, 310, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setText("Gmail");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(790, 150, 130, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("Số điện thoại");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(750, 20, 140, 40);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 255));
        jLabel8.setText("Xác nhận mật khẩu");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 290, 200, 26);

        jTextField5.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(700, 220, 310, 40);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 255));
        jLabel9.setText("Nick Name");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(770, 290, 110, 26);

        jTextField6.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(700, 340, 310, 40);

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(110, 220, 310, 40);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(110, 340, 310, 40);

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 390, 480, 360);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Project\\src\\Register\\add-512.png")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(120, 510, 80, 80);

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(120, 510, 80, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Project\\src\\Register\\biw-game-arcade_hero.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1130, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    File selectedFile;
    String selectedPath;

    public void customerAdd() throws NoSuchAlgorithmException, IOException {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            //db_demo là tên của database, root là username và password là rỗng
            try (Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/epj2_game", "root", "")) {
                //db_demo là tên của database, root là username và password là rỗng
                Statement stmt = con.createStatement();

                String name = jTextField1.getText();
                String password = jPasswordField1.getText();
                String phone = jTextField4.getText();
                String email = jTextField5.getText();
                String nickname = jTextField6.getText();

                MessageDigest md = MessageDigest.getInstance("MD5");
                byte[] messageDigest = md.digest(password.getBytes());
                BigInteger no = new BigInteger(1, messageDigest);
                String hashtext = no.toString(16);
                while (hashtext.length() < 32) {
                    hashtext = "0" + hashtext;
                }
                // Md5 password

                Path source = Paths.get(selectedPath); //original file
                Path targetDir = Paths.get("src/Image");
                Files.createDirectories(targetDir);//in case target directory didn't exist
                Path target = targetDir.resolve(selectedFile.getName());// create new path ending with name content
                Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING);
                // I decided to replace already existing files with same name

                stmt.executeUpdate("INSERT INTO `player`( `user_name`, `password`, `nickname`, `image`, `gmail`, `phone_number`) VALUES ('" + name + "','" + hashtext + "','" + nickname + "','" + target.toString() + "','" + email + "','" + phone + "')");
                System.out.println("sau khi chen ban ghi:");
                ResultSet rs = stmt.executeQuery("Select * from player");
                while (rs.next()) {
                    System.out.println(rs.getInt(1) + " " + rs.getString(2) + "  " + rs.getString(3) + "  " + rs.getString(4) + "  " + rs.getString(5) + "  " + rs.getString(6) + "  " + rs.getString(7));
                }
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
    }

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String name = jTextField1.getText();
        String password = jPasswordField1.getText();
        String password_cf = jPasswordField2.getText();
        String phone = jTextField4.getText();
        String nickname = jTextField6.getText();

        if (name.equals("")) {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập bắt buộc!");
            jTextField1.requestFocusInWindow();
        } else if (!(name.equals("")) && password.length() < 8) {
            JOptionPane.showMessageDialog(this, "Mật khẩu bắt buộc và dài ít nhất 8 kí tự!");
            jPasswordField1.requestFocusInWindow();
        } else if (!(name.equals("")) && password.length() >= 8 && phone.length() < 9) {
            JOptionPane.showMessageDialog(this, "Điện thoại phải có độ dài từ 10 kí tự trở lên!");
            jTextField4.requestFocusInWindow();
        } else if (!(name.equals("")) && password.length() >= 8 && phone.length() >= 9 && ((LineBorder) jTextField5.getBorder()).getLineColor().equals(Color.RED)) {
            JOptionPane.showMessageDialog(this, "Email không hợp lệ!");
            jTextField5.requestFocusInWindow();
        } else if (!(name.equals("")) && password.length() >= 8 && phone.length() >= 9 && ((LineBorder) jTextField5.getBorder()).getLineColor().equals(Color.GREEN)) {
            if (nickname.equals("")) {
                JOptionPane.showMessageDialog(this, "Yêu cầu nhập tên game!");
                jTextField6.requestFocusInWindow();
            } else if (!(nickname.equals("")) && !(password_cf.equals(password))) {
                JOptionPane.showMessageDialog(this, "Mật khẩu không trùng khớp!");
            } else {
                try {
                    try {
                        Class.forName("com.mysql.jdbc.Driver");
                        try (Connection con = DriverManager.getConnection(
                                "jdbc:mysql://localhost:3306/epj2_game", "root", "")) {
                            Statement stateMent = con.createStatement();

                            String sql = "SELECT user_name from player WHERE user_name ='" + name + "'";
                            ResultSet rs = stateMent.executeQuery(sql);

                            if (rs.next()) {
                                JOptionPane.showMessageDialog(this, "Tên tài khoản đã tồn tại!");
                            } else {
                                customerAdd();
                                JOptionPane.showMessageDialog(this, "Đăng kí thành công");
                                new SignIn().setVisible(true);
                                this.setVisible(false);
                            }
                        }
                    } catch (ClassNotFoundException | SQLException e) {
                        System.out.println(e);
                    }
                } catch (NoSuchAlgorithmException | IOException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 10, 10));
        jTextField1.setBorder(new LineBorder(Color.green, 2));
        if (jTextField1.getText().length() < 0) {
            jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 10, 10));
            jTextField1.setBorder(new LineBorder(Color.red, 2));
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        SignIn s = new SignIn();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        String check2 = "^\\d{9}$";
        if (jTextField4.getText().length() < 9 || !jTextField4.getText().matches(check2)) {
            jTextField4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 10, 10));
            jTextField4.setBorder(new LineBorder(Color.red, 2));
        } else {
            jTextField4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 10, 10));
            jTextField4.setBorder(new LineBorder(Color.green, 2));
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        String regex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        if (jTextField5.getText().matches(regex)) {
            jTextField5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 10, 10));
            jTextField5.setBorder(new LineBorder(Color.green, 2));
        } else {
            jTextField5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 10, 10));
            jTextField5.setBorder(new LineBorder(Color.red, 2));
        }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
        jTextField6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 10, 10));
        jTextField6.setBorder(new LineBorder(Color.green, 2));
        if (jTextField6.getText().length() < 0) {
            jTextField6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 10, 10));
            jTextField6.setBorder(new LineBorder(Color.red, 2));
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
        if (jPasswordField1.getText().length() < 8) {
            jPasswordField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 10, 10));
            jPasswordField1.setBorder(new LineBorder(Color.red, 2));
        } else {
            jPasswordField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 10, 10));
            jPasswordField1.setBorder(new LineBorder(Color.green, 2));
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFileChooser j = new JFileChooser();
        j.setLocation(0, 0);
        j.addChoosableFileFilter(new FileNameExtensionFilter("Images", "jpg", "png", "gif", "bmp"));
        int result = j.showSaveDialog(null); 
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = j.getSelectedFile();
            selectedPath = selectedFile.getAbsolutePath();
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(selectedPath).getImage().getScaledInstance(jLabel7.getWidth(), jLabel7.getHeight(), Image.SCALE_DEFAULT));
            jLabel7.setIcon(imageIcon);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Register().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
